# Generated by Django 4.2.19 on 2025-02-07 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Users', '0003_alter_parent_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=50)),
                ('meeting_link', models.URLField()),
                ('scheduled_time', models.DateTimeField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Users.teacher')),
            ],
        ),
    ]
